FROM ubuntu:20.04
MAINTAINER Chungrae Cho <ccr@emstone.com>

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"

RUN apt-get update

RUN apt-get install -y \
  build-essential \
  cmake \
  curl \
  dh-make \
  devscripts \
  dpkg-sig \
  git \
  meson \
  ninja-build \
  sudo \
  ubuntu-dev-tools \
  vim

ARG USER
ARG UID
ARG GID
ARG DOCKER_ROOT

RUN useradd  -G sudo -m ${USER} --uid=${UID} --home-dir $DOCKER_ROOT
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER ${UID}:${GID}

ARG DOCKER_PKGDIR

WORKDIR $DOCKER_PKGDIR

VOLUME [ $DOCKER_PKGDIR ]
